export const khmerToJsMap = {
    // general
    "តាង": "let",
    "ថេរ": "const",
    "អថេរ": "var",
    "មើល": "console.log",
    "មុខងារ": "function",
    "បើកសារ": "/*",
    "បិទសារ": "*/",
    "សារ": "//",
    "\"": "\"",
    "​": " ",
    "១": "1",
    "២": "2",
    "៣": "3",
    "៤": "4",
    "៥": "5",
    "៦": "6",
    "៧": "7",
    "៨": "8",
    "៩": "9",
    "០": "0",
    "ជេសាន់": "JSON.parse",
    "អត្ថបទ": "JSON.stringify",
    ឈប់: "break",
    បន្តរ: "continue",
    ត្រឡប់: "return",
    សាកល្បង: "try",
    ចាប់: "catch",
    បញ្ចប់: "finally",

    // condition
    "ហើយបើ": "else if",
    "បើ": "if",
    "ហើយ": "else",

    // operator
    "បូកបូក": "++",
    "បូក": "+",
    "ដកដក": "--",
    "ដក": "-",
    "គុណ": "*",
    "×": "*",
    "ចែក": "/",
    "សំណល់": "%",
    "ឲឲ": "==",
    "សន": "==",
    "ឲទៅ": "=>",
    "ឲ": "=",
    "ទៅជា": "=>",
    "ឱ្យឱ្យ": "==",
    "ឱ្យ": "=",
    "ស្មើរស្មើរ": "==",
    "ស្មើរ": "=",
    "ធំជាង": ">",
    "ធជ": ">",
    "ធស": ">=",
    "ធំស្មើរ": ">=",
    "តូចជាង": "<",
    "តជ": "<",
    "តូចស្មើរ": "<=",
    "តស": "<=",
    "ផ្ទុយ": "!",
    "ត្រូវ": "true",
    "ខុស": "false",
    "៖": ":",
    "ៈ": ":",
    "««": "{",
    "»»": "}",
    "«": "[",
    "»": "]",

    // HTML DOM
    "ឯកសារ": "document",
    "ទាញលេខ": "getElementById",
    "ទាញអ": "querySelectorAll",
    "ទាញ": "querySelector",

    // Math
    "គណិត": "Math",
    "ចុះ": "floor",
    "ឡើង": "ceil",
    "បង្កត់": "round",
    "ប្រូបាប": "random",

    // Date
    "បរិច្ឆេទ": "Date",
    "យកថ្ងៃ": "getDate",
    "យកខែ": "getMonth",
    "យកឆ្នាំពេញ": "getFullYear",
    "យកឆ្នាំ": "getYear",
    "យកម៉ោង": "getHours",
    "យកនាទី": "getMinutes",
    "យកវិនាទីតូច": "getMilliseconds",
    "យកវិនាទី": "getSeconds",

    // Object, Array, String
    "ផ្ដាច់":"split",
    "បញ្ចូល":"join",
    "ម៉ាទ្រីស":"Array",
    "វត្ថុ":"Object",
    "គន្លឹះ":"keys",
    "ដាក់ដើម":"unshift",
    "ដកដើម":"shift",
    "ដាក់":"push",
    "ដក":"pop",
    "តំណ":"splice",
    "ជាអក្សរ":"toString",
    "រៀប":"sort",
    "ជ្រើស":"filter",

    // Number
    "លេខ": "Number",
    "មកគត់": "parseInt",
    "មកទស្សភាគ": "parseFloat",

    // Loop
    វិលគ្រប់: "forEach",
    វិល: "for",
    ខណៈ :"while",
    ធ្វើ :"do",
    ក្នុង: "in",
    នៃ: "of",
    បញ្ច្រាស់: "reverse",

    // class, function
    ពុម្ភ: "class",
    ថ្មី: "new",
    នេះ: "this",
    ធ្វើត: "extends",
    ត្រាប់: "implements",
    មុខងារ: "function",
    អនុគមន៍: "function",
}