export const khmerToJsMap = {
    // general
    "តាង": "let",
    "ថេរ": "const",
    "អថេរ": "var",
    "មើល": "console.log",
    "មុខងារ": "function",
    "បើកសារ": "/*",
    "បិទសារ": "*/",
    "សារ": "//",
    "\"": "\"",
    "​": " ",
    "១": "1",
    "២": "2",
    "៣": "3",
    "៤": "4",
    "៥": "5",
    "៦": "6",
    "៧": "7",
    "៨": "8",
    "៩": "9",
    "០": "0",
    "ជេសាន់": "JSON.parse",
    "អត្ថបទ": "JSON.stringify",
    ឈប់: "break",
    បន្តរ: "continue",
    ត្រឡប់: "return",
    សាកល្បង: "try",
    ចាប់: "catch",
    បញ្ចប់: "finally",

    // condition
    "ហើយបើ": "else if",
    "បើ": "if",
    "ហើយ": "else",

    // operator
    "បូកបូក": "++",
    "បូក": "+",
    "ដកដក": "--",
    "ដក": "-",
    "គុណ": "*",
    "×": "*",
    "ចែក": "/",
    "សំណល់": "%",
    "ឲឲ": "==",
    "សន": "==",
    "ឲទៅ": "=>",
    "ឲ": "=",
    "ទៅជា": "=>",
    "ឱ្យឱ្យ": "==",
    "ឱ្យ": "=",
    "ស្មើរស្មើរ": "==",
    "ស្មើរ": "=",
    "ធំជាង": ">",
    "ធជ": ">",
    "ធស": ">=",
    "ធំស្មើរ": ">=",
    "តូចជាង": "<",
    "តជ": "<",
    "តូចស្មើរ": "<=",
    "តស": "<=",
    "ផ្ទុយ": "!",
    "ត្រូវ": "true",
    "ខុស": "false",
    "៖": ":",
    "ៈ": ":",
    "««": "{",
    "»»": "}",
    "«": "[",
    "»": "]",

    // HTML DOM
    "ឯកសារ": "document",
    "ទាញលេខ": "getElementById",
    "ទាញអ": "querySelectorAll",
    "ទាញ": "querySelector",
    "បង្កើតធាតុ": "createElement",
    "បន្ថែមធាតុ": "appendChild",
    "ស្ដាប់": "addEventListener",
    "មាតិកា": "innerHTML",
    "អត្ថបទធាតុ": "innerText",
    "តម្លៃ": "value",
    "រចនាប័ទ្ម": "style",
    "ថ្នាក់": "className",
    "បញ្ជីថ្នាក់": "classList",
    "ចុច": "click",
    "ប្ដូរ": "change",
    "បញ្ចូលអត្ថបទ": "input",

    // CSS Properties
    "ពណ៌": "color",
    "ពណ៌ផ្ទៃក្រោយ": "backgroundColor",
    "ទំហំអត្ថបទ": "fontSize",
    "ពុម្ពអក្សរ": "fontFamily",
    "ទទឹង": "width",
    "កម្ពស់": "height",
    "គម្លាតក្រៅ": "margin",
    "គម្លាតក្នុង": "padding",
    "ទីតាំង": "position",
    "កម្រិតពន្លឺ": "opacity",

    // CSS Values (Colors & Others)
    "ក្រហម": "red",
    "ខៀវ": "blue",
    "បៃតង": "green",
    "លឿង": "yellow",
    "ខ្មៅ": "black",
    "ស": "white",
    "ប្រផេះ": "gray",
    "ផ្កាឈូក": "pink",
    "ទឹកក្រូច": "orange",
    "ស្វាយ": "purple",
    "គ្មាន": "none",
    "បិទ": "block",
    "ជួរ": "inline",
    "ភិចសែល": "px",
    "ភាគរយ": "%",
    "សង់ទីម៉ែត្រ": "cm",
    "អ៊ីញ": "in",
    "មីល្លីម៉ែត្រ": "mm",

    // Math
    "គណិត": "Math",
    "ចុះ": "floor",
    "ឡើង": "ceil",
    "បង្កត់": "round",
    "ប្រូបាប": "random",

    // Date
    "បរិច្ឆេទ": "Date",
    "យកថ្ងៃ": "getDate",
    "យកខែ": "getMonth",
    "យកឆ្នាំពេញ": "getFullYear",
    "យកឆ្នាំ": "getYear",
    "យកម៉ោង": "getHours",
    "យកនាទី": "getMinutes",
    "យកវិនាទីតូច": "getMilliseconds",
    "យកវិនាទី": "getSeconds",

    // Object, Array, String
    "ផ្ដាច់":"split",
    "បញ្ចូល":"join",
    "ម៉ាទ្រីស":"Array",
    "វត្ថុ":"Object",
    "គន្លឹះ":"keys",
    "ដាក់ដើម":"unshift",
    "ដកដើម":"shift",
    "ដាក់ចូល":"push",
    "ដកចេញ":"pop",
    "តំណ":"splice",
    "ជាអក្សរ":"toString",
    "រៀប":"sort",
    "ជ្រើស":"filter",

    // Number
    "លេខ": "Number",
    "មកគត់": "parseInt",
    "មកទស្សភាគ": "parseFloat",

    // Loop
    វិលគ្រប់: "forEach",
    វិល: "for",
    ខណៈ :"while",
    ធ្វើ :"do",
    ក្នុង: "in",
    នៃ: "of",
    បញ្ច្រាស់: "reverse",

    // class, function
    ពុម្ភ: "class",
    ថ្មី: "new",
    នេះ: "this",
    ធ្វើត: "extends",
    ត្រាប់: "implements",
    មុខងារ: "function",
    អនុគមន៍: "function",

    // Added Missing
    "ទទេ": "null",
    "មិនទាន់កំណត់": "undefined",
    "ប្រភេទ": "typeof",
    "ប្រវែង": "length",
    "រង់ចាំ": "await",
    "សមកាលកម្ម": "async",
    "រាល់": "setInterval",
    "បន្ទាប់ពី": "setTimeout",
    "ឈប់រាល់": "clearInterval",
    "ឈប់បន្ទាប់ពី": "clearTimeout",
}